### ISSUE TITLE
rawhid build error on Linux with recent versions of gcc

### ISSUE THREAD

**Issue by mkszuba** [pflarue/ardop#162]
Presumably for the sake of portability between Linux and Windows, the variable CM108Handle in the file rawhid.c is declared as a pointer and implicitly cast to int when used as the first argument to read() and write(). gcc has considered casting pointers to integers and back bad practice for quite a while but only produced warnings, current versions however - definitely gcc-14 and up - consider this a compilation error.

Seeing as rawhid already contains Windows-specific bits of code guarded by #ifdef, it would probably make sense to do the same with the declaration of CM108Handle - declaring it as "hid_device *" on Windows but as "int" on systems using POSIX read and write calls.

On a related note, setting CM108Handle to 0 (again for dual-use pointer/integer compatibility reasons I presume) in order to indicate write failure is not quite correct on POSIX systems because it is a valid fd there - standard input by default, as a matter of fact. A negative value would be safer here.

**Comment by pflarue** [comment]
@mkszuba,  I believe that you are compiling from the master branch.  Please try the develop branch to see whether this resolves your difficulties.  The develop branch contains several significant improvements over the master branch.  Among these are some rework of the handling of CM108 devices.

If you still encounter errors or would like to suggest changes, write another comment to this Issue.   I hope to merge develop into master in a few weeks as a part of generating a new release of ardopcf.  So, if you still find a problem in the develop branch, I definitely want to know about it so that it can hopefully be resolved before the new release.  If your concerns are fixed in the develop branch, please let me know and close this Issue.

**Comment by pflarue** [comment]
No response to last comment.  Issue is assumed to be resolved.  Please re-open it if additional help is needed.
